version: '3.8'

services:
  portfolio-web:
    container_name: portfolio-web
    build: .
    command: gunicorn --bind 0.0.0.0:8000 portfolio_project.wsgi:application
    volumes:
      - static_volume:/app/staticfiles
      - ./media:/app/media
      - ./db.sqlite3:/app/db.sqlite3
    env_file:
      - .env
    networks:
      - portfolio_network

volumes:
  static_volume:

networks:
  portfolio_network:
    external: true
    name: angelapinheiro_app-network
